using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace SteamViewer.Tests.Shared;

/// <summary>
/// Captures a stable, sorted, diff-friendly text description of a type's public
/// surface for use in refactor regression tests. Auto-mode gate uses this to detect
/// accidental API visibility changes during partial-class splits / method extracts.
/// </summary>
public static class ApiSurface
{
    public static string Describe(Type type)
    {
        var sb = new StringBuilder();
        sb.Append("# Public API surface\n");
        sb.Append($"# Type: {type.FullName}\n");
        sb.Append($"# Assembly: {type.Assembly.GetName().Name}\n");
        sb.Append("# Generated by ApiSurface.Describe -- do NOT hand-edit\n");
        sb.Append("# Regenerate by setting REGEN_BASELINES=1 and re-running tests\n");
        sb.Append('\n');

        const BindingFlags flags =
            BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        var lines = new List<string>();
        foreach (var m in type.GetMembers(flags))
        {
            if (IsCompilerGenerated(m)) continue;
            var formatted = FormatMember(m);
            if (formatted != null) lines.Add(formatted);
        }
        lines.Sort(StringComparer.Ordinal);

        foreach (var l in lines) sb.Append(l).Append('\n');
        return sb.ToString();
    }

    static bool IsCompilerGenerated(MemberInfo m)
    {
        if (m.IsDefined(typeof(CompilerGeneratedAttribute), false)) return true;
        // Skip auto-generated accessor methods that already show up under their property/event.
        if (m is MethodInfo mi && mi.IsSpecialName) return true;
        // Skip backing-field-like names.
        if (m.Name.StartsWith('<')) return true;
        return false;
    }

    static string? FormatMember(MemberInfo m) => m switch
    {
        ConstructorInfo ci => $"ctor:     {FormatCtor(ci)}",
        MethodInfo mi      => $"method:   {FormatMethod(mi)}",
        PropertyInfo pi    => $"property: {FormatProperty(pi)}",
        EventInfo ei       => $"event:    {FormatEvent(ei)}",
        FieldInfo fi       => $"field:    {FormatField(fi)}",
        Type ti            => $"nested:   {FormatType(ti)}",
        _ => null
    };

    static string FormatType(Type t)
    {
        if (t == typeof(void)) return "void";
        if (t.IsByRef) return $"ref {FormatType(t.GetElementType()!)}";
        if (t.IsArray) return $"{FormatType(t.GetElementType()!)}[]";
        if (t.IsPointer) return $"{FormatType(t.GetElementType()!)}*";
        if (t.IsGenericType)
        {
            var name = t.GetGenericTypeDefinition().Name;
            var idx = name.IndexOf('`');
            if (idx >= 0) name = name[..idx];
            var args = string.Join(", ", t.GetGenericArguments().Select(FormatType));
            return $"{name}<{args}>";
        }
        return t.Name;
    }

    static string FormatMethod(MethodInfo m)
    {
        var modifiers = new List<string>();
        if (m.IsStatic) modifiers.Add("static");
        if (m.IsAbstract) modifiers.Add("abstract");
        else if (m.IsVirtual && !m.IsFinal) modifiers.Add("virtual");
        var mods = modifiers.Count > 0 ? string.Join(' ', modifiers) + ' ' : "";
        var ps = string.Join(", ", m.GetParameters().Select(FormatParam));
        return $"{mods}{FormatType(m.ReturnType)} {m.Name}({ps})";
    }

    static string FormatCtor(ConstructorInfo c)
    {
        var ps = string.Join(", ", c.GetParameters().Select(FormatParam));
        return $".ctor({ps})";
    }

    static string FormatParam(ParameterInfo p)
    {
        var prefix = p.IsOut ? "out " : p.ParameterType.IsByRef ? "ref " : "";
        return $"{prefix}{FormatType(p.ParameterType)} {p.Name}";
    }

    static string FormatProperty(PropertyInfo p)
    {
        var accessors = new List<string>();
        if (p.GetMethod is { IsPublic: true }) accessors.Add("get;");
        if (p.SetMethod is { IsPublic: true }) accessors.Add("set;");
        var acc = accessors.Count > 0 ? string.Join(' ', accessors) : "";
        return $"{FormatType(p.PropertyType)} {p.Name} {{ {acc} }}";
    }

    static string FormatEvent(EventInfo e) =>
        $"{FormatType(e.EventHandlerType!)} {e.Name}";

    static string FormatField(FieldInfo f)
    {
        var modifiers = new List<string>();
        if (f.IsStatic) modifiers.Add("static");
        if (f.IsInitOnly) modifiers.Add("readonly");
        if (f.IsLiteral) modifiers.Add("const");
        var mods = modifiers.Count > 0 ? string.Join(' ', modifiers) + ' ' : "";
        return $"{mods}{FormatType(f.FieldType)} {f.Name}";
    }
}
